services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  redis:
    image: redis/redis-stack:latest
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data

volumes:
  qdrant_data:
  redis_data: