"""added plan column in users table

Revision ID: 2fa2c44ca332
Revises: 43038f040b0b
Create Date: 2025-05-14 01:46:59.087825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2fa2c44ca332'
down_revision: Union[str, None] = '43038f040b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.TEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
