"""chats table added

Revision ID: 6f5f5ad06747
Revises: 40fa25968772
Create Date: 2025-06-27 00:36:10.797847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5f5ad06747'
down_revision: Union[str, None] = '40fa25968772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('role', postgresql.ENUM('user', 'assistant', name='role'), nullable=False))
    op.add_column('chats', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'chats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_column('chats', 'content')
    op.drop_column('chats', 'role')
    # ### end Alembic commands ###
