"""insert_status column added in documents table

Revision ID: c2836813f931
Revises: bc2f87c5bee3
Create Date: 2025-05-22 18:31:16.510580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2836813f931'
down_revision: Union[str, None] = 'bc2f87c5bee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('insert_status', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'documents', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'insert_status')
    # ### end Alembic commands ###
